### ISSUE TITLE
Credentials do not work

### ISSUE THREAD

**Issue by suatgonul** [PrestaShop/live-demo-devices#1]
Hi,

Credentials for backoffice in online demo (http://demo.prestashop.com/en/?view=back) do not work.

email: demo@prestashop.com
pass: prestashop_demo

Getting the following message:

"There is one error.
    The Employee does not exist, or the password provided is incorrect."

**Comment by Quetzacoalt91** [comment]
For all future occurrence of the same issue: This is usually caused by an issue when the demo shop is being instantiated, and requires a manual work directly on the server.
